// <auto-generated />
namespace LibraryBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initilaize_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initilaize_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202206261537192_initilaize_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
